import * as choice from "../func/choice";
import * as combinators from "../func/combinators";
import * as curry from "../func/curry";
import * as option from "../func/option";
import * as tools from "../func/tools";
export * from "../func/choice";
export * from "../func/combinators";
export * from "../func/curry";
export * from "../func/option";
export * from "../func/tools";
export default Object.assign({}, choice, combinators, curry, option, tools);
